# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#  name: demo6-helm-helmrepo
#  namespace: flux-system
#spec:
#  interval: 1m
#  chartRef:
#    kind: OCIRepository
#    name: demo6-source-helm
#    namespace: flux-system
#  values:
#    service:
#      type: LoadBalancer
#      ports:
#        http: 80
#        https: 443
#

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: demo6-helm-helmrepo
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: nginx
      version: 23.0.3
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: demo6-source-helm
        namespace: flux-system
  values:
    service:
      type: LoadBalancer
      ports:
        http: 80
        https: 443
